/* Autogenerated 2025-08-04 21:11:21.868597 */
#include "cpu_bin_tests.h"

const bus_result_t adc_abs_results[] = {
    { 0x2013, 0x6d, true },
    { 0x2014, 0x02, true },
    { 0x2015, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t adc_absx_results[] = {
    { 0x2014, 0x7d, true },
    { 0x2015, 0x02, true },
    { 0x2016, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t adc_absx_page_results[] = {
    { 0x2015, 0x7d, true },
    { 0x2016, 0xff, true },
    { 0x2017, 0x30, true },
    { 0x2017, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t adc_absy_results[] = {
    { 0x2014, 0x79, true },
    { 0x2015, 0x02, true },
    { 0x2016, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t adc_absy_page_results[] = {
    { 0x2015, 0x79, true },
    { 0x2016, 0xff, true },
    { 0x2017, 0x30, true },
    { 0x2017, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t adc_apx_ind_results[] = {
    { 0x201d, 0x61, true },
    { 0x201e, 0x03, true },
    { 0x201e, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t adc_imm_results[] = {
    { 0x2010, 0x69, true },
    { 0x2011, 0x01, true },
};

const bus_result_t adc_zp_results[] = {
    { 0x2012, 0x65, true },
    { 0x2013, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t adc_zp_ind_results[] = {
    { 0x2019, 0x72, true },
    { 0x201a, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t adc_zpx_results[] = {
    { 0x2013, 0x75, true },
    { 0x2014, 0x02, true },
    { 0x2014, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t adc_zpy_ind_results[] = {
    { 0x2018, 0x71, true },
    { 0x2019, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t adc_zpy_ind_page_results[] = {
    { 0x201b, 0x71, true },
    { 0x201c, 0x03, true },
    { 0x0003, 0xff, true },
    { 0x0004, 0x30, true },
    { 0x0004, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t and_abs_results[] = {
    { 0x200d, 0x2d, true },
    { 0x200e, 0x02, true },
    { 0x200f, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t and_absx_results[] = {
    { 0x200f, 0x3d, true },
    { 0x2010, 0x02, true },
    { 0x2011, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t and_absx_page_results[] = {
    { 0x2014, 0x3d, true },
    { 0x2015, 0xff, true },
    { 0x2016, 0x30, true },
    { 0x2016, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t and_absy_results[] = {
    { 0x200f, 0x39, true },
    { 0x2010, 0x02, true },
    { 0x2011, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t and_absy_page_results[] = {
    { 0x2014, 0x39, true },
    { 0x2015, 0xff, true },
    { 0x2016, 0x30, true },
    { 0x2016, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t and_imm_results[] = {
    { 0x200d, 0x29, true },
    { 0x200e, 0x55, true },
};

const bus_result_t and_zp_results[] = {
    { 0x200d, 0x25, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t and_zp_ind_results[] = {
    { 0x2015, 0x32, true },
    { 0x2016, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t and_zpx_results[] = {
    { 0x200f, 0x35, true },
    { 0x2010, 0x02, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t and_zpx_ind_results[] = {
    { 0x2017, 0x21, true },
    { 0x2018, 0x03, true },
    { 0x2018, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t and_zpy_ind_results[] = {
    { 0x2017, 0x31, true },
    { 0x2018, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t and_zpy_ind_page_results[] = {
    { 0x201a, 0x31, true },
    { 0x201b, 0x03, true },
    { 0x0003, 0xff, true },
    { 0x0004, 0x30, true },
    { 0x0004, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t asl_a_results[] = {
    { 0x200f, 0x0a, true },
    { 0x2010, 0xa9, true },
};

const bus_result_t asl_abs_results[] = {
    { 0x200d, 0x0e, true },
    { 0x200e, 0x02, true },
    { 0x200f, 0x30, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
};

const bus_result_t asl_absx_results[] = {
    { 0x200f, 0x1e, true },
    { 0x2010, 0x02, true },
    { 0x2011, 0x30, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
};

const bus_result_t asl_absx_page_results[] = {
    { 0x2014, 0x1e, true },
    { 0x2015, 0xff, true },
    { 0x2016, 0x30, true },
    { 0x2016, 0x30, true },
    { 0x3100, 0x00, true },
    { 0x3100, 0x00, true },
    { 0x3100, 0x00, true },
};

const bus_result_t asl_zp_results[] = {
    { 0x200d, 0x06, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
};

const bus_result_t asl_zpx_results[] = {
    { 0x200f, 0x16, true },
    { 0x2010, 0x02, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
};

const bus_result_t bbr_br_results[] = {
    { 0x200f, 0x0f, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x2011, 0x01, true },
    { 0x2012, 0xea, true },
};

const bus_result_t bbr_br_page_results[] = {
    { 0x30fc, 0x0f, true },
    { 0x30fd, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x30fe, 0x01, true },
    { 0x30ff, 0xea, true },
    { 0x30ff, 0xea, true },
};

const bus_result_t bbr_nobr_results[] = {
    { 0x2011, 0x0f, true },
    { 0x2012, 0x02, true },
    { 0x0002, 0x01, true },
    { 0x0002, 0x01, true },
    { 0x2013, 0x01, true },
};

const bus_result_t bbs_br_results[] = {
    { 0x2011, 0x8f, true },
    { 0x2012, 0x02, true },
    { 0x0002, 0x01, true },
    { 0x0002, 0x01, true },
    { 0x2013, 0x01, true },
    { 0x2014, 0xea, true },
};

const bus_result_t bbs_br_page_results[] = {
    { 0x30fc, 0x8f, true },
    { 0x30fd, 0x02, true },
    { 0x0002, 0x01, true },
    { 0x0002, 0x01, true },
    { 0x30fe, 0x01, true },
    { 0x30ff, 0xea, true },
    { 0x30ff, 0xea, true },
};

const bus_result_t bbs_nobr_results[] = {
    { 0x200f, 0x8f, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x2011, 0x01, true },
};

const bus_result_t bcc_br_results[] = {
    { 0x200e, 0x90, true },
    { 0x200f, 0x01, true },
    { 0x2010, 0xea, true },
};

const bus_result_t bcc_br_page_results[] = {
    { 0x30fd, 0x90, true },
    { 0x30fe, 0x01, true },
    { 0x30ff, 0xea, true },
    { 0x30ff, 0xea, true },
};

const bus_result_t bcc_nobr_results[] = {
    { 0x200e, 0x90, true },
    { 0x200f, 0x01, true },
};

const bus_result_t bcs_br_results[] = {
    { 0x200e, 0xb0, true },
    { 0x200f, 0x01, true },
    { 0x2010, 0xea, true },
};

const bus_result_t bcs_br_page_results[] = {
    { 0x30fd, 0xb0, true },
    { 0x30fe, 0x01, true },
    { 0x30ff, 0xea, true },
    { 0x30ff, 0xea, true },
};

const bus_result_t bcs_nobr_results[] = {
    { 0x200e, 0xb0, true },
    { 0x200f, 0x01, true },
};

const bus_result_t beq_br_results[] = {
    { 0x2011, 0xf0, true },
    { 0x2012, 0x01, true },
    { 0x2013, 0xea, true },
};

const bus_result_t beq_br_page_results[] = {
    { 0x30fd, 0xf0, true },
    { 0x30fe, 0x01, true },
    { 0x30ff, 0xea, true },
    { 0x30ff, 0xea, true },
};

const bus_result_t beq_nobr_results[] = {
    { 0x2011, 0xf0, true },
    { 0x2012, 0x01, true },
};

const bus_result_t bit_abs_results[] = {
    { 0x200d, 0x2c, true },
    { 0x200e, 0x02, true },
    { 0x200f, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t bit_absx_results[] = {
    { 0x200f, 0x3c, true },
    { 0x2010, 0x02, true },
    { 0x2011, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t bit_absx_page_results[] = {
    { 0x2014, 0x3c, true },
    { 0x2015, 0xff, true },
    { 0x2016, 0x30, true },
    { 0x2016, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t bit_imm_results[] = {
    { 0x200f, 0x89, true },
    { 0x2010, 0x01, true },
};

const bus_result_t bit_zp_results[] = {
    { 0x200d, 0x24, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t bit_zpx_results[] = {
    { 0x200f, 0x34, true },
    { 0x2010, 0x02, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t bmi_br_results[] = {
    { 0x2012, 0x30, true },
    { 0x2013, 0x01, true },
    { 0x2014, 0xea, true },
};

const bus_result_t bmi_br_page_results[] = {
    { 0x30fd, 0x30, true },
    { 0x30fe, 0x01, true },
    { 0x30ff, 0xea, true },
    { 0x30ff, 0xea, true },
};

const bus_result_t bmi_nobr_results[] = {
    { 0x200f, 0x30, true },
    { 0x2010, 0x01, true },
};

const bus_result_t bne_br_results[] = {
    { 0x2011, 0xd0, true },
    { 0x2012, 0x01, true },
    { 0x2013, 0xea, true },
};

const bus_result_t bne_br_page_results[] = {
    { 0x30fd, 0xd0, true },
    { 0x30fe, 0x01, true },
    { 0x30ff, 0xea, true },
    { 0x30ff, 0xea, true },
};

const bus_result_t bne_nobr_results[] = {
    { 0x2011, 0xd0, true },
    { 0x2012, 0x01, true },
};

const bus_result_t bpl_br_results[] = {
    { 0x200f, 0x10, true },
    { 0x2010, 0x01, true },
    { 0x2011, 0xea, true },
};

const bus_result_t bpl_br_page_results[] = {
    { 0x30fd, 0x10, true },
    { 0x30fe, 0x01, true },
    { 0x30ff, 0xea, true },
    { 0x30ff, 0xea, true },
};

const bus_result_t bpl_nobr_results[] = {
    { 0x2011, 0x10, true },
    { 0x2012, 0x01, true },
};

const bus_result_t bra_results[] = {
    { 0x200d, 0x80, true },
    { 0x200e, 0x01, true },
    { 0x200f, 0xea, true },
};

const bus_result_t bra_page_results[] = {
    { 0x30fd, 0x80, true },
    { 0x30fe, 0x01, true },
    { 0x30ff, 0xea, true },
    { 0x30ff, 0xea, true },
};

const bus_result_t bvc_br_results[] = {
    { 0x2012, 0x50, true },
    { 0x2013, 0x01, true },
    { 0x2014, 0xea, true },
};

const bus_result_t bvc_br_page_results[] = {
    { 0x30fd, 0x50, true },
    { 0x30fe, 0x01, true },
    { 0x30ff, 0xea, true },
    { 0x30ff, 0xea, true },
};

const bus_result_t bvc_nobr_results[] = {
    { 0x2012, 0x50, true },
    { 0x2013, 0x01, true },
};

const bus_result_t bvs_br_results[] = {
    { 0x2012, 0x70, true },
    { 0x2013, 0x01, true },
    { 0x2014, 0xea, true },
};

const bus_result_t bvs_br_page_results[] = {
    { 0x30fd, 0x70, true },
    { 0x30fe, 0x01, true },
    { 0x30ff, 0xea, true },
    { 0x30ff, 0xea, true },
};

const bus_result_t bvs_nobr_results[] = {
    { 0x2012, 0x70, true },
    { 0x2013, 0x01, true },
};

const bus_result_t clc_results[] = {
    { 0x200d, 0x18, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t cld_results[] = {
    { 0x200d, 0xd8, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t cli_results[] = {
    { 0x200d, 0x58, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t clv_results[] = {
    { 0x200d, 0xb8, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t cmp_abs_results[] = {
    { 0x200d, 0xcd, true },
    { 0x200e, 0x02, true },
    { 0x200f, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t cmp_absx_page_results[] = {
    { 0x200f, 0xdd, true },
    { 0x2010, 0xff, true },
    { 0x2011, 0x30, true },
    { 0x2011, 0x30, true },
    { 0x3100, 0x4c, true },
};

const bus_result_t cmp_absy_results[] = {
    { 0x200f, 0xd9, true },
    { 0x2010, 0x02, true },
    { 0x2011, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t cmp_absy_page_results[] = {
    { 0x200f, 0xd9, true },
    { 0x2010, 0xff, true },
    { 0x2011, 0x30, true },
    { 0x2011, 0x30, true },
    { 0x3100, 0x4c, true },
};

const bus_result_t cmp_abx_results[] = {
    { 0x200f, 0xdd, true },
    { 0x2010, 0x02, true },
    { 0x2011, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t cmp_imm_results[] = {
    { 0x200d, 0xc9, true },
    { 0x200e, 0x01, true },
};

const bus_result_t cmp_zp_results[] = {
    { 0x200d, 0xc5, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t cmp_zp_ind_results[] = {
    { 0x2015, 0xd2, true },
    { 0x2016, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t cmp_zpx_results[] = {
    { 0x200f, 0xd5, true },
    { 0x2010, 0x02, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t cmp_zpx_ind_results[] = {
    { 0x201a, 0xc1, true },
    { 0x201b, 0x03, true },
    { 0x201b, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t cmp_zpy_ind_results[] = {
    { 0x2017, 0xd1, true },
    { 0x2018, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t cmp_zpy_ind_page_results[] = {
    { 0x2017, 0xd1, true },
    { 0x2018, 0x03, true },
    { 0x0003, 0xff, true },
    { 0x0004, 0x30, true },
    { 0x0004, 0x30, true },
    { 0x3100, 0x4c, true },
};

const bus_result_t cpx_abs_results[] = {
    { 0x200d, 0xec, true },
    { 0x200e, 0x02, true },
    { 0x200f, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t cpx_imm_results[] = {
    { 0x200d, 0xe0, true },
    { 0x200e, 0x00, true },
};

const bus_result_t cpx_zp_results[] = {
    { 0x200d, 0xe4, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t cpy_abs_results[] = {
    { 0x200d, 0xcc, true },
    { 0x200e, 0x02, true },
    { 0x200f, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t cpy_imm_results[] = {
    { 0x200d, 0xc0, true },
    { 0x200e, 0x00, true },
};

const bus_result_t cpy_zp_results[] = {
    { 0x200d, 0xc4, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t dec_a_results[] = {
    { 0x200d, 0x3a, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t dec_abs_results[] = {
    { 0x200d, 0xce, true },
    { 0x200e, 0x02, true },
    { 0x200f, 0x30, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0xff, true },
};

const bus_result_t dec_absx_results[] = {
    { 0x200f, 0xde, true },
    { 0x2010, 0x02, true },
    { 0x2011, 0x30, true },
    { 0x3002, 0xff, true },
    { 0x3002, 0xff, true },
    { 0x3002, 0xff, true },
    { 0x3002, 0xfe, true },
};

const bus_result_t dec_absx_page_results[] = {
    { 0x200f, 0xde, true },
    { 0x2010, 0xff, true },
    { 0x2011, 0x30, true },
    { 0x2011, 0x30, true },
    { 0x3100, 0x4c, true },
    { 0x3100, 0x4c, true },
    { 0x3100, 0x4b, true },
};

const bus_result_t dec_zp_results[] = {
    { 0x200d, 0xc6, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0xff, true },
};

const bus_result_t dec_zpx_results[] = {
    { 0x200f, 0xd6, true },
    { 0x2010, 0x02, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0xff, true },
    { 0x0002, 0xff, true },
    { 0x0002, 0xfe, true },
};

const bus_result_t dex_results[] = {
    { 0x200d, 0xca, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t dey_results[] = {
    { 0x200d, 0x88, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t eor_abs_results[] = {
    { 0x2012, 0x4d, true },
    { 0x2013, 0x02, true },
    { 0x2014, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t eor_absx_results[] = {
    { 0x2014, 0x5d, true },
    { 0x2015, 0x02, true },
    { 0x2016, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t eor_absx_page_results[] = {
    { 0x2014, 0x5d, true },
    { 0x2015, 0xff, true },
    { 0x2016, 0x30, true },
    { 0x2016, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t eor_asby_results[] = {
    { 0x2014, 0x59, true },
    { 0x2015, 0x02, true },
    { 0x2016, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t eor_imm_results[] = {
    { 0x200f, 0x49, true },
    { 0x2010, 0x01, true },
};

const bus_result_t eor_zp_results[] = {
    { 0x2011, 0x45, true },
    { 0x2012, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t eor_zp_ind_results[] = {
    { 0x201a, 0x52, true },
    { 0x201b, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t eor_zpx_results[] = {
    { 0x2013, 0x55, true },
    { 0x2014, 0x02, true },
    { 0x2014, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t eor_zpx_ind_results[] = {
    { 0x201c, 0x41, true },
    { 0x201d, 0x03, true },
    { 0x201d, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t eor_zpy_ind_results[] = {
    { 0x201c, 0x51, true },
    { 0x201d, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t eor_zpy_ind_page_results[] = {
    { 0x201a, 0x51, true },
    { 0x201b, 0x03, true },
    { 0x0003, 0xff, true },
    { 0x0004, 0x30, true },
    { 0x0004, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t inc_a_results[] = {
    { 0x200d, 0x1a, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t inc_abs_results[] = {
    { 0x200d, 0xee, true },
    { 0x200e, 0x02, true },
    { 0x200f, 0x30, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x01, true },
};

const bus_result_t inc_absx_results[] = {
    { 0x200f, 0xfe, true },
    { 0x2010, 0x02, true },
    { 0x2011, 0x30, true },
    { 0x3002, 0x01, true },
    { 0x3002, 0x01, true },
    { 0x3002, 0x01, true },
    { 0x3002, 0x02, true },
};

const bus_result_t inc_absx_page_results[] = {
    { 0x200f, 0xfe, true },
    { 0x2010, 0xff, true },
    { 0x2011, 0x30, true },
    { 0x2011, 0x30, true },
    { 0x3100, 0x00, true },
    { 0x3100, 0x00, true },
    { 0x3100, 0x01, true },
};

const bus_result_t inc_zp_results[] = {
    { 0x200d, 0xe6, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x01, true },
};

const bus_result_t inc_zpx_results[] = {
    { 0x200f, 0xf6, true },
    { 0x2010, 0x02, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0x01, true },
    { 0x0002, 0x01, true },
    { 0x0002, 0x02, true },
};

const bus_result_t inx_results[] = {
    { 0x200d, 0xe8, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t iny_results[] = {
    { 0x200d, 0xc8, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t jmp_abs_results[] = {
    { 0x200d, 0x4c, true },
    { 0x200e, 0x12, true },
    { 0x200f, 0x20, true },
};

const bus_result_t jmp_abs_ind_results[] = {
    { 0x2017, 0x6c, true },
    { 0x2018, 0x00, true },
    { 0x2019, 0x30, true },
    { 0x2019, 0x30, true },
    { 0x3000, 0x1b, true },
    { 0x3001, 0x20, true },
};

const bus_result_t jmp_absx_ind_results[] = {
    { 0x2019, 0x7c, true },
    { 0x201a, 0x00, true },
    { 0x201b, 0x30, true },
    { 0x201b, 0x30, true },
    { 0x3000, 0x1d, true },
    { 0x3001, 0x20, true },
};

const bus_result_t jsr_results[] = {
    { 0x200d, 0x20, true },
    { 0x200e, 0x15, true },
    { 0x01ff, 0x20, true },
    { 0x01ff, 0x20, true },
    { 0x01fe, 0x0f, true },
    { 0x200f, 0x20, true },
};

const bus_result_t lda_abs_results[] = {
    { 0x2010, 0xad, true },
    { 0x2011, 0x02, true },
    { 0x2012, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t lda_absx_results[] = {
    { 0x2012, 0xbd, true },
    { 0x2013, 0x02, true },
    { 0x2014, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t lda_absx_page_results[] = {
    { 0x2012, 0xbd, true },
    { 0x2013, 0xff, true },
    { 0x2014, 0x30, true },
    { 0x2014, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t lda_absy_results[] = {
    { 0x2012, 0xb9, true },
    { 0x2013, 0x02, true },
    { 0x2014, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t lda_absy_page_results[] = {
    { 0x2012, 0xb9, true },
    { 0x2013, 0xff, true },
    { 0x2014, 0x30, true },
    { 0x2014, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t lda_imm_results[] = {
    { 0x200d, 0xa9, true },
    { 0x200e, 0x00, true },
};

const bus_result_t lda_zp_results[] = {
    { 0x200d, 0xa5, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x02, true },
};

const bus_result_t lda_zp_ind_results[] = {
    { 0x2015, 0xb2, true },
    { 0x2016, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t lda_zpx_results[] = {
    { 0x2011, 0xb5, true },
    { 0x2012, 0x02, true },
    { 0x2012, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t lda_zpx_ind_results[] = {
    { 0x2017, 0xa1, true },
    { 0x2018, 0x03, true },
    { 0x2018, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t lda_zpy_ind_results[] = {
    { 0x201a, 0xb1, true },
    { 0x201b, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t lda_zpy_ind_page_results[] = {
    { 0x201a, 0xb1, true },
    { 0x201b, 0x03, true },
    { 0x0003, 0xff, true },
    { 0x0004, 0x30, true },
    { 0x0004, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t ldx_abs_results[] = {
    { 0x2010, 0xae, true },
    { 0x2011, 0x02, true },
    { 0x2012, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t ldx_absy_results[] = {
    { 0x2012, 0xbe, true },
    { 0x2013, 0x02, true },
    { 0x2014, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t ldx_absy_page_results[] = {
    { 0x2012, 0xbe, true },
    { 0x2013, 0xff, true },
    { 0x2014, 0x30, true },
    { 0x2014, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t ldx_imm_results[] = {
    { 0x200d, 0xa2, true },
    { 0x200e, 0x00, true },
};

const bus_result_t ldx_zp_results[] = {
    { 0x200d, 0xa6, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t ldx_zpy_results[] = {
    { 0x2011, 0xb6, true },
    { 0x2012, 0x02, true },
    { 0x2012, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t ldy_abs_results[] = {
    { 0x2010, 0xac, true },
    { 0x2011, 0x02, true },
    { 0x2012, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t ldy_absx_results[] = {
    { 0x2012, 0xbc, true },
    { 0x2013, 0x02, true },
    { 0x2014, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t ldy_absx_page_results[] = {
    { 0x2012, 0xbc, true },
    { 0x2013, 0xff, true },
    { 0x2014, 0x30, true },
    { 0x2014, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t ldy_imm_results[] = {
    { 0x200d, 0xa0, true },
    { 0x200e, 0x00, true },
};

const bus_result_t ldy_zp_results[] = {
    { 0x200d, 0xa4, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t ldy_zpx_results[] = {
    { 0x2011, 0xb4, true },
    { 0x2012, 0x02, true },
    { 0x2012, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t lsr_a_results[] = {
    { 0x200f, 0x4a, true },
    { 0x2010, 0xa9, true },
};

const bus_result_t lsr_abs_results[] = {
    { 0x2012, 0x4e, true },
    { 0x2013, 0x02, true },
    { 0x2014, 0x30, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
};

const bus_result_t lsr_absx_results[] = {
    { 0x2014, 0x5e, true },
    { 0x2015, 0x02, true },
    { 0x2016, 0x30, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
};

const bus_result_t lsr_absx_page_results[] = {
    { 0x2014, 0x5e, true },
    { 0x2015, 0xff, true },
    { 0x2016, 0x30, true },
    { 0x2016, 0x30, true },
    { 0x3100, 0x00, true },
    { 0x3100, 0x00, true },
    { 0x3100, 0x00, true },
};

const bus_result_t lsr_zp_results[] = {
    { 0x2011, 0x46, true },
    { 0x2012, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
};

const bus_result_t lsr_zpx_results[] = {
    { 0x2013, 0x56, true },
    { 0x2014, 0x02, true },
    { 0x2014, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
};

const bus_result_t nop_results[] = {
    { 0x200d, 0xea, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t ora_abs_results[] = {
    { 0x200d, 0x0d, true },
    { 0x200e, 0x02, true },
    { 0x200f, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t ora_absx_results[] = {
    { 0x200f, 0x1d, true },
    { 0x2010, 0x02, true },
    { 0x2011, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t ora_absx_page_results[] = {
    { 0x2014, 0x1d, true },
    { 0x2015, 0xff, true },
    { 0x2016, 0x30, true },
    { 0x2016, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t ora_absy_results[] = {
    { 0x200f, 0x19, true },
    { 0x2010, 0x02, true },
    { 0x2011, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t ora_absy_page_results[] = {
    { 0x2014, 0x19, true },
    { 0x2015, 0xff, true },
    { 0x2016, 0x30, true },
    { 0x2016, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t ora_imm_results[] = {
    { 0x200d, 0x09, true },
    { 0x200e, 0x01, true },
};

const bus_result_t ora_zp_results[] = {
    { 0x200f, 0x05, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t ora_zp_ind_results[] = {
    { 0x2015, 0x12, true },
    { 0x2016, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t ora_zpx_results[] = {
    { 0x200f, 0x15, true },
    { 0x2010, 0x02, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t ora_zpx_ind_results[] = {
    { 0x200f, 0x01, true },
    { 0x2010, 0x03, true },
    { 0x2010, 0x03, true },
    { 0x0005, 0x00, true },
    { 0x0006, 0x00, true },
    { 0x0000, 0x0f, true },
};

const bus_result_t ora_zpy_ind_results[] = {
    { 0x2017, 0x11, true },
    { 0x2018, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t ora_zpy_ind_page_results[] = {
    { 0x201a, 0x11, true },
    { 0x201b, 0x03, true },
    { 0x0003, 0xff, true },
    { 0x0004, 0x30, true },
    { 0x0004, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t pha_results[] = {
    { 0x200d, 0x48, true },
    { 0x200e, 0xa9, true },
    { 0x01ff, 0x20, true },
};

const bus_result_t php_results[] = {
    { 0x200d, 0x08, true },
    { 0x200e, 0xa9, true },
    { 0x01ff, 0x34, true },
};

const bus_result_t phx_results[] = {
    { 0x200d, 0xda, true },
    { 0x200e, 0xa9, true },
    { 0x01ff, 0xff, true },
};

const bus_result_t phy_results[] = {
    { 0x200d, 0x5a, true },
    { 0x200e, 0xa9, true },
    { 0x01ff, 0x01, true },
};

const bus_result_t pla_results[] = {
    { 0x2010, 0x68, true },
    { 0x2011, 0xa9, true },
    { 0x01fe, 0x0f, true },
    { 0x01ff, 0x55, true },
};

const bus_result_t plp_results[] = {
    { 0x200e, 0x28, true },
    { 0x200f, 0xa9, true },
    { 0x01fe, 0x0f, true },
    { 0x01ff, 0x34, true },
};

const bus_result_t plx_results[] = {
    { 0x200e, 0xfa, true },
    { 0x200f, 0xa9, true },
    { 0x01fe, 0x0f, true },
    { 0x01ff, 0xff, true },
};

const bus_result_t ply_results[] = {
    { 0x200e, 0x7a, true },
    { 0x200f, 0xa9, true },
    { 0x01fe, 0x0f, true },
    { 0x01ff, 0x01, true },
};

const bus_result_t rmb_results[] = {
    { 0x200d, 0x07, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
};

const bus_result_t rol_a_results[] = {
    { 0x200d, 0x2a, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t rol_abs_results[] = {
    { 0x2010, 0x2e, true },
    { 0x2011, 0x02, true },
    { 0x2012, 0x30, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
};

const bus_result_t rol_absx_results[] = {
    { 0x2012, 0x3e, true },
    { 0x2013, 0x02, true },
    { 0x2014, 0x30, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
};

const bus_result_t rol_absx_page_results[] = {
    { 0x2014, 0x3e, true },
    { 0x2015, 0xff, true },
    { 0x2016, 0x30, true },
    { 0x2016, 0x30, true },
    { 0x3100, 0x00, true },
    { 0x3100, 0x00, true },
    { 0x3100, 0x00, true },
};

const bus_result_t rol_zp_results[] = {
    { 0x200f, 0x26, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
};

const bus_result_t rol_zpx_results[] = {
    { 0x2011, 0x36, true },
    { 0x2012, 0x02, true },
    { 0x2012, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
};

const bus_result_t ror_a_results[] = {
    { 0x200f, 0x6a, true },
    { 0x2010, 0xa9, true },
};

const bus_result_t ror_abs_results[] = {
    { 0x200d, 0x6e, true },
    { 0x200e, 0x02, true },
    { 0x200f, 0x30, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
};

const bus_result_t ror_absx_results[] = {
    { 0x2012, 0x7e, true },
    { 0x2013, 0x02, true },
    { 0x2014, 0x30, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
};

const bus_result_t ror_zp_results[] = {
    { 0x2011, 0x66, true },
    { 0x2012, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
};

const bus_result_t ror_zpx_results[] = {
    { 0x2011, 0x76, true },
    { 0x2012, 0x02, true },
    { 0x2012, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
};

const bus_result_t rts_results[] = {
    { 0x2016, 0x60, true },
    { 0x2017, 0x58, true },
    { 0x01fd, 0x30, true },
    { 0x01fe, 0x0f, true },
    { 0x01ff, 0x20, true },
    { 0x200f, 0x20, true },
};

const bus_result_t sbc_abs_results[] = {
    { 0x2011, 0xed, true },
    { 0x2012, 0x02, true },
    { 0x2013, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t sbc_absx_results[] = {
    { 0x2013, 0xfd, true },
    { 0x2014, 0x02, true },
    { 0x2015, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t sbc_absx_page_results[] = {
    { 0x2015, 0xfd, true },
    { 0x2016, 0xff, true },
    { 0x2017, 0x30, true },
    { 0x2017, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t sbc_absy_results[] = {
    { 0x2013, 0xf9, true },
    { 0x2014, 0x02, true },
    { 0x2015, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t sbc_absy_page_results[] = {
    { 0x2015, 0xf9, true },
    { 0x2016, 0xff, true },
    { 0x2017, 0x30, true },
    { 0x2017, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t sbc_imm_results[] = {
    { 0x200e, 0xe9, true },
    { 0x200f, 0x00, true },
};

const bus_result_t sbc_zp_results[] = {
    { 0x2010, 0xe5, true },
    { 0x2011, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t sbc_zp_ind_results[] = {
    { 0x2019, 0xf2, true },
    { 0x201a, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t sbc_zpx_results[] = {
    { 0x2012, 0xf5, true },
    { 0x2013, 0x02, true },
    { 0x2013, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t sbc_zpx_ind_results[] = {
    { 0x201b, 0xe1, true },
    { 0x201c, 0x03, true },
    { 0x201c, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t sbc_zpy_ind_results[] = {
    { 0x201b, 0xf1, true },
    { 0x201c, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t sbc_zpy_ind_page_results[] = {
    { 0x201b, 0xf1, true },
    { 0x201c, 0x03, true },
    { 0x0003, 0xff, true },
    { 0x0004, 0x30, true },
    { 0x0004, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t sec_results[] = {
    { 0x200d, 0x38, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t sed_results[] = {
    { 0x200d, 0xf8, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t sei_results[] = {
    { 0x200d, 0x78, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t smb_results[] = {
    { 0x200d, 0x87, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x01, true },
};

const bus_result_t sta_abs_results[] = {
    { 0x200f, 0x8d, true },
    { 0x2010, 0x02, true },
    { 0x2011, 0x30, true },
    { 0x3002, 0x01, true },
};

const bus_result_t sta_absx_results[] = {
    { 0x2011, 0x9d, true },
    { 0x2012, 0x02, true },
    { 0x2013, 0x30, true },
    { 0x3007, 0x00, true },
    { 0x3007, 0x00, true },
};

const bus_result_t sta_absx_page_results[] = {
    { 0x2011, 0x9d, true },
    { 0x2012, 0xff, true },
    { 0x2013, 0x30, true },
    { 0x2013, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t sta_absy_results[] = {
    { 0x2011, 0x99, true },
    { 0x2012, 0x02, true },
    { 0x2013, 0x30, true },
    { 0x3002, 0x01, true },
    { 0x3002, 0x00, true },
};

const bus_result_t sta_absy_page_results[] = {
    { 0x2011, 0x99, true },
    { 0x2012, 0xff, true },
    { 0x2013, 0x30, true },
    { 0x2013, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t sta_zp_results[] = {
    { 0x200f, 0x85, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0x01, true },
};

const bus_result_t sta_zp_ind_results[] = {
    { 0x2017, 0x92, true },
    { 0x2018, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x01, true },
};

const bus_result_t sta_zpx_results[] = {
    { 0x2011, 0x95, true },
    { 0x2012, 0x02, true },
    { 0x2012, 0x02, true },
    { 0x0002, 0x01, true },
};

const bus_result_t sta_zpx_ind_results[] = {
    { 0x2019, 0x81, true },
    { 0x201a, 0x03, true },
    { 0x201a, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x55, true },
};

const bus_result_t sta_zpy_ind_results[] = {
    { 0x2019, 0x91, true },
    { 0x201a, 0x03, true },
    { 0x0003, 0x02, true },
    { 0x0004, 0x30, true },
    { 0x0004, 0x30, true },
    { 0x3002, 0x01, true },
};

const bus_result_t sta_zpy_ind_page_results[] = {
    { 0x201c, 0x91, true },
    { 0x201d, 0x03, true },
    { 0x0003, 0xff, true },
    { 0x0004, 0x30, true },
    { 0x0004, 0x30, true },
    { 0x3100, 0x01, true },
};

const bus_result_t stx_abs_results[] = {
    { 0x200f, 0x8e, true },
    { 0x2010, 0x02, true },
    { 0x2011, 0x30, true },
    { 0x3002, 0x01, true },
};

const bus_result_t stx_zp_results[] = {
    { 0x200f, 0x86, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0x01, true },
};

const bus_result_t stx_zpy_results[] = {
    { 0x2011, 0x96, true },
    { 0x2012, 0x02, true },
    { 0x2012, 0x02, true },
    { 0x0002, 0x01, true },
};

const bus_result_t sty_abs_results[] = {
    { 0x200f, 0x8c, true },
    { 0x2010, 0x02, true },
    { 0x2011, 0x30, true },
    { 0x3002, 0x01, true },
};

const bus_result_t sty_zp_results[] = {
    { 0x200f, 0x84, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0x01, true },
};

const bus_result_t sty_zpx_results[] = {
    { 0x2011, 0x94, true },
    { 0x2012, 0x02, true },
    { 0x2012, 0x02, true },
    { 0x0002, 0x01, true },
};

const bus_result_t stz_abs_results[] = {
    { 0x200d, 0x9c, true },
    { 0x200e, 0x02, true },
    { 0x200f, 0x30, true },
    { 0x3002, 0x00, true },
};

const bus_result_t stz_absx_results[] = {
    { 0x200f, 0x9e, true },
    { 0x2010, 0x02, true },
    { 0x2011, 0x30, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
};

const bus_result_t stz_absx_page_results[] = {
    { 0x200f, 0x9e, true },
    { 0x2010, 0xff, true },
    { 0x2011, 0x30, true },
    { 0x2011, 0x30, true },
    { 0x3100, 0x00, true },
};

const bus_result_t stz_zp_results[] = {
    { 0x200d, 0x64, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t stz_zpx_results[] = {
    { 0x200f, 0x74, true },
    { 0x2010, 0x02, true },
    { 0x2010, 0x02, true },
    { 0x0002, 0x00, true },
};

const bus_result_t tax_results[] = {
    { 0x200d, 0xaa, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t tay_results[] = {
    { 0x200d, 0xa8, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t trb_abs_results[] = {
    { 0x200d, 0x1c, true },
    { 0x200e, 0x02, true },
    { 0x200f, 0x30, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
};

const bus_result_t trb_zp_results[] = {
    { 0x200d, 0x14, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
};

const bus_result_t tsb_abs_results[] = {
    { 0x200d, 0x0c, true },
    { 0x200e, 0x02, true },
    { 0x200f, 0x30, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x00, true },
    { 0x3002, 0x20, true },
};

const bus_result_t tsb_zp_results[] = {
    { 0x200d, 0x04, true },
    { 0x200e, 0x02, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x00, true },
    { 0x0002, 0x20, true },
};

const bus_result_t tsx_results[] = {
    { 0x200d, 0xba, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t txa_results[] = {
    { 0x200d, 0x8a, true },
    { 0x200e, 0xa9, true },
};

const bus_result_t txs_results[] = {
    { 0x200f, 0x9a, true },
    { 0x2010, 0xa9, true },
};

const bus_result_t tya_results[] = {
    { 0x200d, 0x98, true },
    { 0x200e, 0xa9, true },
};

const cpu_bin_test_info_t cpu_bin_tests[] =
{
    {
        "adc_abs",
        "adc_abs.bin",
        4,
        adc_abs_results
    },
    {
        "adc_absx",
        "adc_absx.bin",
        4,
        adc_absx_results
    },
    {
        "adc_absx_page",
        "adc_absx_page.bin",
        5,
        adc_absx_page_results
    },
    {
        "adc_absy",
        "adc_absy.bin",
        4,
        adc_absy_results
    },
    {
        "adc_absy_page",
        "adc_absy_page.bin",
        5,
        adc_absy_page_results
    },
    {
        "adc_apx_ind",
        "adc_apx_ind.bin",
        6,
        adc_apx_ind_results
    },
    {
        "adc_imm",
        "adc_imm.bin",
        2,
        adc_imm_results
    },
    {
        "adc_zp",
        "adc_zp.bin",
        3,
        adc_zp_results
    },
    {
        "adc_zp_ind",
        "adc_zp_ind.bin",
        5,
        adc_zp_ind_results
    },
    {
        "adc_zpx",
        "adc_zpx.bin",
        4,
        adc_zpx_results
    },
    {
        "adc_zpy_ind",
        "adc_zpy_ind.bin",
        5,
        adc_zpy_ind_results
    },
    {
        "adc_zpy_ind_page",
        "adc_zpy_ind_page.bin",
        6,
        adc_zpy_ind_page_results
    },
    {
        "and_abs",
        "and_abs.bin",
        4,
        and_abs_results
    },
    {
        "and_absx",
        "and_absx.bin",
        4,
        and_absx_results
    },
    {
        "and_absx_page",
        "and_absx_page.bin",
        5,
        and_absx_page_results
    },
    {
        "and_absy",
        "and_absy.bin",
        4,
        and_absy_results
    },
    {
        "and_absy_page",
        "and_absy_page.bin",
        5,
        and_absy_page_results
    },
    {
        "and_imm",
        "and_imm.bin",
        2,
        and_imm_results
    },
    {
        "and_zp",
        "and_zp.bin",
        3,
        and_zp_results
    },
    {
        "and_zp_ind",
        "and_zp_ind.bin",
        5,
        and_zp_ind_results
    },
    {
        "and_zpx",
        "and_zpx.bin",
        4,
        and_zpx_results
    },
    {
        "and_zpx_ind",
        "and_zpx_ind.bin",
        6,
        and_zpx_ind_results
    },
    {
        "and_zpy_ind",
        "and_zpy_ind.bin",
        5,
        and_zpy_ind_results
    },
    {
        "and_zpy_ind_page",
        "and_zpy_ind_page.bin",
        6,
        and_zpy_ind_page_results
    },
    {
        "asl_a",
        "asl_a.bin",
        2,
        asl_a_results
    },
    {
        "asl_abs",
        "asl_abs.bin",
        6,
        asl_abs_results
    },
    {
        "asl_absx",
        "asl_absx.bin",
        6,
        asl_absx_results
    },
    {
        "asl_absx_page",
        "asl_absx_page.bin",
        7,
        asl_absx_page_results
    },
    {
        "asl_zp",
        "asl_zp.bin",
        5,
        asl_zp_results
    },
    {
        "asl_zpx",
        "asl_zpx.bin",
        6,
        asl_zpx_results
    },
    {
        "bbr_br",
        "bbr_br.bin",
        6,
        bbr_br_results
    },
    {
        "bbr_br_page",
        "bbr_br_page.bin",
        7,
        bbr_br_page_results
    },
    {
        "bbr_nobr",
        "bbr_nobr.bin",
        5,
        bbr_nobr_results
    },
    {
        "bbs_br",
        "bbs_br.bin",
        6,
        bbs_br_results
    },
    {
        "bbs_br_page",
        "bbs_br_page.bin",
        7,
        bbs_br_page_results
    },
    {
        "bbs_nobr",
        "bbs_nobr.bin",
        5,
        bbs_nobr_results
    },
    {
        "bcc_br",
        "bcc_br.bin",
        3,
        bcc_br_results
    },
    {
        "bcc_br_page",
        "bcc_br_page.bin",
        4,
        bcc_br_page_results
    },
    {
        "bcc_nobr",
        "bcc_nobr.bin",
        2,
        bcc_nobr_results
    },
    {
        "bcs_br",
        "bcs_br.bin",
        3,
        bcs_br_results
    },
    {
        "bcs_br_page",
        "bcs_br_page.bin",
        4,
        bcs_br_page_results
    },
    {
        "bcs_nobr",
        "bcs_nobr.bin",
        2,
        bcs_nobr_results
    },
    {
        "beq_br",
        "beq_br.bin",
        3,
        beq_br_results
    },
    {
        "beq_br_page",
        "beq_br_page.bin",
        4,
        beq_br_page_results
    },
    {
        "beq_nobr",
        "beq_nobr.bin",
        2,
        beq_nobr_results
    },
    {
        "bit_abs",
        "bit_abs.bin",
        4,
        bit_abs_results
    },
    {
        "bit_absx",
        "bit_absx.bin",
        4,
        bit_absx_results
    },
    {
        "bit_absx_page",
        "bit_absx_page.bin",
        5,
        bit_absx_page_results
    },
    {
        "bit_imm",
        "bit_imm.bin",
        2,
        bit_imm_results
    },
    {
        "bit_zp",
        "bit_zp.bin",
        3,
        bit_zp_results
    },
    {
        "bit_zpx",
        "bit_zpx.bin",
        4,
        bit_zpx_results
    },
    {
        "bmi_br",
        "bmi_br.bin",
        3,
        bmi_br_results
    },
    {
        "bmi_br_page",
        "bmi_br_page.bin",
        4,
        bmi_br_page_results
    },
    {
        "bmi_nobr",
        "bmi_nobr.bin",
        2,
        bmi_nobr_results
    },
    {
        "bne_br",
        "bne_br.bin",
        3,
        bne_br_results
    },
    {
        "bne_br_page",
        "bne_br_page.bin",
        4,
        bne_br_page_results
    },
    {
        "bne_nobr",
        "bne_nobr.bin",
        2,
        bne_nobr_results
    },
    {
        "bpl_br",
        "bpl_br.bin",
        3,
        bpl_br_results
    },
    {
        "bpl_br_page",
        "bpl_br_page.bin",
        4,
        bpl_br_page_results
    },
    {
        "bpl_nobr",
        "bpl_nobr.bin",
        2,
        bpl_nobr_results
    },
    {
        "bra",
        "bra.bin",
        3,
        bra_results
    },
    {
        "bra_page",
        "bra_page.bin",
        4,
        bra_page_results
    },
    {
        "bvc_br",
        "bvc_br.bin",
        3,
        bvc_br_results
    },
    {
        "bvc_br_page",
        "bvc_br_page.bin",
        4,
        bvc_br_page_results
    },
    {
        "bvc_nobr",
        "bvc_nobr.bin",
        2,
        bvc_nobr_results
    },
    {
        "bvs_br",
        "bvs_br.bin",
        3,
        bvs_br_results
    },
    {
        "bvs_br_page",
        "bvs_br_page.bin",
        4,
        bvs_br_page_results
    },
    {
        "bvs_nobr",
        "bvs_nobr.bin",
        2,
        bvs_nobr_results
    },
    {
        "clc",
        "clc.bin",
        2,
        clc_results
    },
    {
        "cld",
        "cld.bin",
        2,
        cld_results
    },
    {
        "cli",
        "cli.bin",
        2,
        cli_results
    },
    {
        "clv",
        "clv.bin",
        2,
        clv_results
    },
    {
        "cmp_abs",
        "cmp_abs.bin",
        4,
        cmp_abs_results
    },
    {
        "cmp_absx_page",
        "cmp_absx_page.bin",
        5,
        cmp_absx_page_results
    },
    {
        "cmp_absy",
        "cmp_absy.bin",
        4,
        cmp_absy_results
    },
    {
        "cmp_absy_page",
        "cmp_absy_page.bin",
        5,
        cmp_absy_page_results
    },
    {
        "cmp_abx",
        "cmp_abx.bin",
        4,
        cmp_abx_results
    },
    {
        "cmp_imm",
        "cmp_imm.bin",
        2,
        cmp_imm_results
    },
    {
        "cmp_zp",
        "cmp_zp.bin",
        3,
        cmp_zp_results
    },
    {
        "cmp_zp_ind",
        "cmp_zp_ind.bin",
        5,
        cmp_zp_ind_results
    },
    {
        "cmp_zpx",
        "cmp_zpx.bin",
        4,
        cmp_zpx_results
    },
    {
        "cmp_zpx_ind",
        "cmp_zpx_ind.bin",
        6,
        cmp_zpx_ind_results
    },
    {
        "cmp_zpy_ind",
        "cmp_zpy_ind.bin",
        5,
        cmp_zpy_ind_results
    },
    {
        "cmp_zpy_ind_page",
        "cmp_zpy_ind_page.bin",
        6,
        cmp_zpy_ind_page_results
    },
    {
        "cpx_abs",
        "cpx_abs.bin",
        4,
        cpx_abs_results
    },
    {
        "cpx_imm",
        "cpx_imm.bin",
        2,
        cpx_imm_results
    },
    {
        "cpx_zp",
        "cpx_zp.bin",
        3,
        cpx_zp_results
    },
    {
        "cpy_abs",
        "cpy_abs.bin",
        4,
        cpy_abs_results
    },
    {
        "cpy_imm",
        "cpy_imm.bin",
        2,
        cpy_imm_results
    },
    {
        "cpy_zp",
        "cpy_zp.bin",
        3,
        cpy_zp_results
    },
    {
        "dec_a",
        "dec_a.bin",
        2,
        dec_a_results
    },
    {
        "dec_abs",
        "dec_abs.bin",
        6,
        dec_abs_results
    },
    {
        "dec_absx",
        "dec_absx.bin",
        7,
        dec_absx_results
    },
    {
        "dec_absx_page",
        "dec_absx_page.bin",
        7,
        dec_absx_page_results
    },
    {
        "dec_zp",
        "dec_zp.bin",
        5,
        dec_zp_results
    },
    {
        "dec_zpx",
        "dec_zpx.bin",
        6,
        dec_zpx_results
    },
    {
        "dex",
        "dex.bin",
        2,
        dex_results
    },
    {
        "dey",
        "dey.bin",
        2,
        dey_results
    },
    {
        "eor_abs",
        "eor_abs.bin",
        4,
        eor_abs_results
    },
    {
        "eor_absx",
        "eor_absx.bin",
        4,
        eor_absx_results
    },
    {
        "eor_absx_page",
        "eor_absx_page.bin",
        5,
        eor_absx_page_results
    },
    {
        "eor_asby",
        "eor_asby.bin",
        4,
        eor_asby_results
    },
    {
        "eor_imm",
        "eor_imm.bin",
        2,
        eor_imm_results
    },
    {
        "eor_zp",
        "eor_zp.bin",
        3,
        eor_zp_results
    },
    {
        "eor_zp_ind",
        "eor_zp_ind.bin",
        5,
        eor_zp_ind_results
    },
    {
        "eor_zpx",
        "eor_zpx.bin",
        4,
        eor_zpx_results
    },
    {
        "eor_zpx_ind",
        "eor_zpx_ind.bin",
        6,
        eor_zpx_ind_results
    },
    {
        "eor_zpy_ind",
        "eor_zpy_ind.bin",
        5,
        eor_zpy_ind_results
    },
    {
        "eor_zpy_ind_page",
        "eor_zpy_ind_page.bin",
        6,
        eor_zpy_ind_page_results
    },
    {
        "inc_a",
        "inc_a.bin",
        2,
        inc_a_results
    },
    {
        "inc_abs",
        "inc_abs.bin",
        6,
        inc_abs_results
    },
    {
        "inc_absx",
        "inc_absx.bin",
        7,
        inc_absx_results
    },
    {
        "inc_absx_page",
        "inc_absx_page.bin",
        7,
        inc_absx_page_results
    },
    {
        "inc_zp",
        "inc_zp.bin",
        5,
        inc_zp_results
    },
    {
        "inc_zpx",
        "inc_zpx.bin",
        6,
        inc_zpx_results
    },
    {
        "inx",
        "inx.bin",
        2,
        inx_results
    },
    {
        "iny",
        "iny.bin",
        2,
        iny_results
    },
    {
        "jmp_abs",
        "jmp_abs.bin",
        3,
        jmp_abs_results
    },
    {
        "jmp_abs_ind",
        "jmp_abs_ind.bin",
        6,
        jmp_abs_ind_results
    },
    {
        "jmp_absx_ind",
        "jmp_absx_ind.bin",
        6,
        jmp_absx_ind_results
    },
    {
        "jsr",
        "jsr.bin",
        6,
        jsr_results
    },
    {
        "lda_abs",
        "lda_abs.bin",
        4,
        lda_abs_results
    },
    {
        "lda_absx",
        "lda_absx.bin",
        4,
        lda_absx_results
    },
    {
        "lda_absx_page",
        "lda_absx_page.bin",
        5,
        lda_absx_page_results
    },
    {
        "lda_absy",
        "lda_absy.bin",
        4,
        lda_absy_results
    },
    {
        "lda_absy_page",
        "lda_absy_page.bin",
        5,
        lda_absy_page_results
    },
    {
        "lda_imm",
        "lda_imm.bin",
        2,
        lda_imm_results
    },
    {
        "lda_zp",
        "lda_zp.bin",
        3,
        lda_zp_results
    },
    {
        "lda_zp_ind",
        "lda_zp_ind.bin",
        5,
        lda_zp_ind_results
    },
    {
        "lda_zpx",
        "lda_zpx.bin",
        4,
        lda_zpx_results
    },
    {
        "lda_zpx_ind",
        "lda_zpx_ind.bin",
        6,
        lda_zpx_ind_results
    },
    {
        "lda_zpy_ind",
        "lda_zpy_ind.bin",
        5,
        lda_zpy_ind_results
    },
    {
        "lda_zpy_ind_page",
        "lda_zpy_ind_page.bin",
        6,
        lda_zpy_ind_page_results
    },
    {
        "ldx_abs",
        "ldx_abs.bin",
        4,
        ldx_abs_results
    },
    {
        "ldx_absy",
        "ldx_absy.bin",
        4,
        ldx_absy_results
    },
    {
        "ldx_absy_page",
        "ldx_absy_page.bin",
        5,
        ldx_absy_page_results
    },
    {
        "ldx_imm",
        "ldx_imm.bin",
        2,
        ldx_imm_results
    },
    {
        "ldx_zp",
        "ldx_zp.bin",
        3,
        ldx_zp_results
    },
    {
        "ldx_zpy",
        "ldx_zpy.bin",
        4,
        ldx_zpy_results
    },
    {
        "ldy_abs",
        "ldy_abs.bin",
        4,
        ldy_abs_results
    },
    {
        "ldy_absx",
        "ldy_absx.bin",
        4,
        ldy_absx_results
    },
    {
        "ldy_absx_page",
        "ldy_absx_page.bin",
        5,
        ldy_absx_page_results
    },
    {
        "ldy_imm",
        "ldy_imm.bin",
        2,
        ldy_imm_results
    },
    {
        "ldy_zp",
        "ldy_zp.bin",
        3,
        ldy_zp_results
    },
    {
        "ldy_zpx",
        "ldy_zpx.bin",
        4,
        ldy_zpx_results
    },
    {
        "lsr_a",
        "lsr_a.bin",
        2,
        lsr_a_results
    },
    {
        "lsr_abs",
        "lsr_abs.bin",
        6,
        lsr_abs_results
    },
    {
        "lsr_absx",
        "lsr_absx.bin",
        6,
        lsr_absx_results
    },
    {
        "lsr_absx_page",
        "lsr_absx_page.bin",
        7,
        lsr_absx_page_results
    },
    {
        "lsr_zp",
        "lsr_zp.bin",
        5,
        lsr_zp_results
    },
    {
        "lsr_zpx",
        "lsr_zpx.bin",
        6,
        lsr_zpx_results
    },
    {
        "nop",
        "nop.bin",
        2,
        nop_results
    },
    {
        "ora_abs",
        "ora_abs.bin",
        4,
        ora_abs_results
    },
    {
        "ora_absx",
        "ora_absx.bin",
        4,
        ora_absx_results
    },
    {
        "ora_absx_page",
        "ora_absx_page.bin",
        5,
        ora_absx_page_results
    },
    {
        "ora_absy",
        "ora_absy.bin",
        4,
        ora_absy_results
    },
    {
        "ora_absy_page",
        "ora_absy_page.bin",
        5,
        ora_absy_page_results
    },
    {
        "ora_imm",
        "ora_imm.bin",
        2,
        ora_imm_results
    },
    {
        "ora_zp",
        "ora_zp.bin",
        3,
        ora_zp_results
    },
    {
        "ora_zp_ind",
        "ora_zp_ind.bin",
        5,
        ora_zp_ind_results
    },
    {
        "ora_zpx",
        "ora_zpx.bin",
        4,
        ora_zpx_results
    },
    {
        "ora_zpx_ind",
        "ora_zpx_ind.bin",
        6,
        ora_zpx_ind_results
    },
    {
        "ora_zpy_ind",
        "ora_zpy_ind.bin",
        5,
        ora_zpy_ind_results
    },
    {
        "ora_zpy_ind_page",
        "ora_zpy_ind_page.bin",
        6,
        ora_zpy_ind_page_results
    },
    {
        "pha",
        "pha.bin",
        3,
        pha_results
    },
    {
        "php",
        "php.bin",
        3,
        php_results
    },
    {
        "phx",
        "phx.bin",
        3,
        phx_results
    },
    {
        "phy",
        "phy.bin",
        3,
        phy_results
    },
    {
        "pla",
        "pla.bin",
        4,
        pla_results
    },
    {
        "plp",
        "plp.bin",
        4,
        plp_results
    },
    {
        "plx",
        "plx.bin",
        4,
        plx_results
    },
    {
        "ply",
        "ply.bin",
        4,
        ply_results
    },
    {
        "rmb",
        "rmb.bin",
        5,
        rmb_results
    },
    {
        "rol_a",
        "rol_a.bin",
        2,
        rol_a_results
    },
    {
        "rol_abs",
        "rol_abs.bin",
        6,
        rol_abs_results
    },
    {
        "rol_absx",
        "rol_absx.bin",
        6,
        rol_absx_results
    },
    {
        "rol_absx_page",
        "rol_absx_page.bin",
        7,
        rol_absx_page_results
    },
    {
        "rol_zp",
        "rol_zp.bin",
        5,
        rol_zp_results
    },
    {
        "rol_zpx",
        "rol_zpx.bin",
        6,
        rol_zpx_results
    },
    {
        "ror_a",
        "ror_a.bin",
        2,
        ror_a_results
    },
    {
        "ror_abs",
        "ror_abs.bin",
        6,
        ror_abs_results
    },
    {
        "ror_absx",
        "ror_absx.bin",
        6,
        ror_absx_results
    },
    {
        "ror_zp",
        "ror_zp.bin",
        5,
        ror_zp_results
    },
    {
        "ror_zpx",
        "ror_zpx.bin",
        6,
        ror_zpx_results
    },
    {
        "rts",
        "rts.bin",
        6,
        rts_results
    },
    {
        "sbc_abs",
        "sbc_abs.bin",
        4,
        sbc_abs_results
    },
    {
        "sbc_absx",
        "sbc_absx.bin",
        4,
        sbc_absx_results
    },
    {
        "sbc_absx_page",
        "sbc_absx_page.bin",
        5,
        sbc_absx_page_results
    },
    {
        "sbc_absy",
        "sbc_absy.bin",
        4,
        sbc_absy_results
    },
    {
        "sbc_absy_page",
        "sbc_absy_page.bin",
        5,
        sbc_absy_page_results
    },
    {
        "sbc_imm",
        "sbc_imm.bin",
        2,
        sbc_imm_results
    },
    {
        "sbc_zp",
        "sbc_zp.bin",
        3,
        sbc_zp_results
    },
    {
        "sbc_zp_ind",
        "sbc_zp_ind.bin",
        5,
        sbc_zp_ind_results
    },
    {
        "sbc_zpx",
        "sbc_zpx.bin",
        4,
        sbc_zpx_results
    },
    {
        "sbc_zpx_ind",
        "sbc_zpx_ind.bin",
        6,
        sbc_zpx_ind_results
    },
    {
        "sbc_zpy_ind",
        "sbc_zpy_ind.bin",
        5,
        sbc_zpy_ind_results
    },
    {
        "sbc_zpy_ind_page",
        "sbc_zpy_ind_page.bin",
        6,
        sbc_zpy_ind_page_results
    },
    {
        "sec",
        "sec.bin",
        2,
        sec_results
    },
    {
        "sed",
        "sed.bin",
        2,
        sed_results
    },
    {
        "sei",
        "sei.bin",
        2,
        sei_results
    },
    {
        "smb",
        "smb.bin",
        5,
        smb_results
    },
    {
        "sta_abs",
        "sta_abs.bin",
        4,
        sta_abs_results
    },
    {
        "sta_absx",
        "sta_absx.bin",
        5,
        sta_absx_results
    },
    {
        "sta_absx_page",
        "sta_absx_page.bin",
        5,
        sta_absx_page_results
    },
    {
        "sta_absy",
        "sta_absy.bin",
        5,
        sta_absy_results
    },
    {
        "sta_absy_page",
        "sta_absy_page.bin",
        5,
        sta_absy_page_results
    },
    {
        "sta_zp",
        "sta_zp.bin",
        3,
        sta_zp_results
    },
    {
        "sta_zp_ind",
        "sta_zp_ind.bin",
        5,
        sta_zp_ind_results
    },
    {
        "sta_zpx",
        "sta_zpx.bin",
        4,
        sta_zpx_results
    },
    {
        "sta_zpx_ind",
        "sta_zpx_ind.bin",
        6,
        sta_zpx_ind_results
    },
    {
        "sta_zpy_ind",
        "sta_zpy_ind.bin",
        6,
        sta_zpy_ind_results
    },
    {
        "sta_zpy_ind_page",
        "sta_zpy_ind_page.bin",
        6,
        sta_zpy_ind_page_results
    },
    {
        "stx_abs",
        "stx_abs.bin",
        4,
        stx_abs_results
    },
    {
        "stx_zp",
        "stx_zp.bin",
        3,
        stx_zp_results
    },
    {
        "stx_zpy",
        "stx_zpy.bin",
        4,
        stx_zpy_results
    },
    {
        "sty_abs",
        "sty_abs.bin",
        4,
        sty_abs_results
    },
    {
        "sty_zp",
        "sty_zp.bin",
        3,
        sty_zp_results
    },
    {
        "sty_zpx",
        "sty_zpx.bin",
        4,
        sty_zpx_results
    },
    {
        "stz_abs",
        "stz_abs.bin",
        4,
        stz_abs_results
    },
    {
        "stz_absx",
        "stz_absx.bin",
        5,
        stz_absx_results
    },
    {
        "stz_absx_page",
        "stz_absx_page.bin",
        5,
        stz_absx_page_results
    },
    {
        "stz_zp",
        "stz_zp.bin",
        3,
        stz_zp_results
    },
    {
        "stz_zpx",
        "stz_zpx.bin",
        4,
        stz_zpx_results
    },
    {
        "tax",
        "tax.bin",
        2,
        tax_results
    },
    {
        "tay",
        "tay.bin",
        2,
        tay_results
    },
    {
        "trb_abs",
        "trb_abs.bin",
        6,
        trb_abs_results
    },
    {
        "trb_zp",
        "trb_zp.bin",
        5,
        trb_zp_results
    },
    {
        "tsb_abs",
        "tsb_abs.bin",
        6,
        tsb_abs_results
    },
    {
        "tsb_zp",
        "tsb_zp.bin",
        5,
        tsb_zp_results
    },
    {
        "tsx",
        "tsx.bin",
        2,
        tsx_results
    },
    {
        "txa",
        "txa.bin",
        2,
        txa_results
    },
    {
        "txs",
        "txs.bin",
        2,
        txs_results
    },
    {
        "tya",
        "tya.bin",
        2,
        tya_results
    }
};

const uint32_t cpu_num_bin_tests = sizeof(cpu_bin_tests)/sizeof(cpu_bin_test_info_t);
