from argparse import ArgumentParser
import yaml
import os
import datetime
import os

FILE_HEADER = '''\
/* Autogenerated {} */
#include "cpu_bin_tests.h"

'''

BUS_RESULT_LIST_FMT = '''\
const bus_result_t {}_results[] = {{
{}
}};

'''

BUS_RESULT_FMT = '''\
    {{ {}, {}, {} }},\
'''

TEST_INFO_FMT = '''\
    {{
        "{test_name}",
        "{test}",
        {cycles},
        {test_name}_results
    }}'''

TEST_INFO_LIST_FMT = '''\
const cpu_bin_test_info_t cpu_bin_tests[] =
{{
{}
}};

'''

FILE_FOOTER = '''\
const uint32_t cpu_num_bin_tests = sizeof(cpu_bin_tests)/sizeof(cpu_bin_test_info_t);
'''

def main():
    parser = ArgumentParser()
    parser.add_argument('testlist')
    parser.add_argument('-o','--output',default='cpu_bin_tests.c')
    parser.add_argument('-d', '--testdir', default='.')

    args = parser.parse_args()

    with open(args.testlist, 'r') as testlist_file, open(args.output, 'w+') as outfile:
        outfile.write(FILE_HEADER.format(datetime.datetime.now()))
        testlist = yaml.safe_load(testlist_file)

        test_infos = []

        for test in testlist:
            print(test)
            busops = []

            for op in test['busops']:
                op_split = op.strip().split()
                busops.append(BUS_RESULT_FMT.format(op_split[1], op_split[2], 'true'))

            opslist = '\n'.join(busops)
            liststruct = BUS_RESULT_LIST_FMT.format(test['test_name'], opslist)

            outfile.write(liststruct)

            if args.testdir != '.':
                test['test'] = os.path.join(args.testdir, test['test'])

            test_infos.append(TEST_INFO_FMT.format(**test))

        testinfo_list = TEST_INFO_LIST_FMT.format(',\n'.join(test_infos))
        outfile.write(testinfo_list);
        outfile.write(FILE_FOOTER)




if __name__ == '__main__':
    main()
