# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: main

    - uses: actions/checkout@v4
      with:
        repository: ThrowTheSwitch/Unity
        ref: v2.5.2
        path: unity

    - name: Install ncurses
      run: |
        sudo apt-get install -y libncurses-dev

    - name: Configure Unity
      run: cmake -B ${{github.workspace}}/unity/build -S ${{github.workspace}}/unity

    - name: Build Unity
      run: cmake --build ${{github.workspace}}/unity/build

    - name: Install Unity
      run: sudo cmake --install ${{github.workspace}}/unity/build

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/main/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_TESTING=ON -S ${{github.workspace}}/main

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/main/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/main/build
      run: ctest -C ${{env.BUILD_TYPE}}

